import { Edit3, Plus, Search, Trash2, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import DataState from './DataState';
import StatusBadge from './StatusBadge';
import { PageHeader } from '../pages/DashboardShared';

const display = (value) => value === true ? 'Available' : value === false ? 'Unavailable' : value == null || value === '' ? '—' : String(value);
export default function ResourceManager({ title, subtitle, api, idKey, columns, fields = [], canCreate = true, canEdit = true, canDelete = true, defaults = {}, actions = [] }) {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [search, setSearch] = useState('');
  const [editing, setEditing] = useState(null); const [form, setForm] = useState(defaults); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { setRecords(await api.list()); } catch (e) { setError(e); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => records.filter((row) => JSON.stringify(row).toLowerCase().includes(search.toLowerCase())), [records, search]);
  const open = (row = null) => { setEditing(row || {}); setForm(row ? Object.fromEntries(fields.map((field) => [field.name, field.type === 'date' && row[field.name] ? String(row[field.name]).slice(0, 10) : row[field.name] ?? ''])) : { ...defaults }); };
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(null); try { const body = Object.fromEntries(fields.map((field) => [field.name, field.type === 'number' ? Number(form[field.name] || 0) : field.type === 'checkbox' ? Boolean(form[field.name]) : form[field.name]])); if (editing?.[idKey]) await api.update(editing[idKey], body); else await api.create(body); setEditing(null); await load(); } catch (e) { setError(e); } finally { setBusy(false); } };
  const remove = async (row) => { if (!window.confirm(`Delete ${row[idKey]}? This action is recorded in the audit log.`)) return; setBusy(true); try { await api.remove(row[idKey]); await load(); } catch (e) { setError(e); } finally { setBusy(false); } };
  const runAction = async (action, row) => { setBusy(true); setError(null); try { await action.run(row); await load(); } catch (e) { setError(e); } finally { setBusy(false); } };
  return <><PageHeader eyebrow="SafeHome operations" title={title} subtitle={subtitle} action={canCreate ? <button className="primary-button" onClick={() => open()}><Plus size={17}/> Add record</button> : null}/>
    <section className="content-card resource-card"><div className="table-toolbar"><label className="search-control"><Search size={17}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}`}/></label><span className="result-count">{filtered.length} records</span></div>
    <DataState loading={loading} error={error} onRetry={load}/>{!loading && !error && <div className="table-wrap"><table><thead><tr>{columns.map((column) => <th key={column.key}>{column.label}</th>)}{(canEdit || canDelete || actions.length > 0) && <th>Actions</th>}</tr></thead><tbody>{filtered.map((row) => <tr key={row[idKey]}>{columns.map((column) => <td key={column.key}>{column.badge ? <StatusBadge>{display(row[column.key])}</StatusBadge> : display(row[column.key])}</td>)}{(canEdit || canDelete || actions.length > 0) && <td><div className="row-actions">{actions.filter((a) => !a.show || a.show(row)).map((action) => <button key={action.label} className="table-action" disabled={busy} onClick={() => runAction(action, row)}>{action.label}</button>)}{canEdit && <button className="icon-action" onClick={() => open(row)} title="Edit"><Edit3 size={15}/></button>}{canDelete && <button className="icon-action danger" onClick={() => remove(row)} title="Delete"><Trash2 size={15}/></button>}</div></td>}</tr>)}</tbody></table>{filtered.length === 0 && <p className="empty-row">No records match this view.</p>}</div>}</section>
    {editing && <div className="modal-backdrop"><form className="resource-modal" onSubmit={submit}><div className="modal-head"><div><span className="section-kicker">{editing[idKey] ? 'Update record' : 'New record'}</span><h2>{editing[idKey] || title}</h2></div><button type="button" className="icon-action" onClick={() => setEditing(null)}><X/></button></div><div className="resource-form">{fields.map((field) => <label key={field.name}>{field.label}{field.type === 'select' ? <select value={form[field.name] ?? ''} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} required={field.required}><option value="">Select</option>{field.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : field.type === 'checkbox' ? <input type="checkbox" checked={Boolean(form[field.name])} onChange={(e) => setForm({ ...form, [field.name]: e.target.checked })}/> : field.type === 'textarea' ? <textarea rows="4" value={form[field.name] ?? ''} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} required={field.required}/> : <input type={field.type || 'text'} value={form[field.name] ?? ''} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} required={field.required}/>}</label>)}</div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditing(null)}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save record'}</button></div></form></div>}
  </>;
}
