import { Archive, Bell, BookOpen, Bot, BrainCircuit, Building2, CalendarDays, Car, ClipboardList, CreditCard, FileBarChart, FileText, Home, LayoutDashboard, ListChecks, Network, Package, ParkingCircle, PlusCircle, ScrollText, ShieldCheck, UserRoundCheck, Users, Wrench, X } from 'lucide-react';
import { NavLink } from 'react-router-dom';

const commonAdmin = [
  ['/residents','Residents',Users], ['/tickets','Tickets',ListChecks], ['/work-orders','Work Orders',ClipboardList], ['/billing','Billing',CreditCard], ['/visitors','Visitors',UserRoundCheck], ['/parking','Parking',ParkingCircle], ['/notices','Notices',Bell], ['/reports','Reports',FileBarChart],
];
const links = {
  MAIN_ADMIN: [['/main-admin/dashboard','Dashboard',LayoutDashboard],['/ai-insights','AI Insights',BrainCircuit],['/collective-incidents','Collective Incidents',Network],['/knowledge-support','Knowledge Support',BookOpen],['/ai-chatbot','AI Chatbot',Bot],['/communities','Communities',Home],['/blocks','Blocks',Building2],['/apartments','Apartments',Archive],...commonAdmin.slice(0,3),['/technicians','Technicians',Wrench],['/vendors','Vendors',Building2],...commonAdmin.slice(3,5),['/amenities','Amenities',CalendarDays],['/bookings','Bookings',BookOpen],...commonAdmin.slice(6,7),['/documents','Documents',FileText],['/inventory','Inventory',Package],...commonAdmin.slice(7),['/audit-logs','Audit Logs',ScrollText]],
  BLOCK_SUB_ADMIN: [['/block-admin/dashboard','Dashboard',LayoutDashboard],['/ai-insights','AI Insights',BrainCircuit],['/collective-incidents','Collective Incidents',Network],['/knowledge-support','Knowledge Support',BookOpen],['/ai-chatbot','AI Chatbot',Bot],...commonAdmin],
  RESIDENT: [['/resident/dashboard','Dashboard',LayoutDashboard],['/ai-chatbot','AI Chatbot',Bot],['/resident/create-complaint','Create Complaint',PlusCircle],['/tickets','My Tickets',ListChecks],['/billing','My Bills',CreditCard],['/visitors','Visitors',UserRoundCheck],['/vehicles','Vehicles',Car],['/amenities','Amenities',CalendarDays],['/bookings','My Bookings',BookOpen],['/notices','Notices',Bell],['/documents','Documents',FileText]],
  TECHNICIAN: [['/technician/dashboard','Dashboard',LayoutDashboard],['/knowledge-support','Knowledge Support',BookOpen],['/ai-chatbot','AI Chatbot',Bot],['/work-orders','Assigned Work Orders',ClipboardList],['/tickets','Tickets',ListChecks]],
  SECURITY: [['/security/dashboard','Security Dashboard',ShieldCheck],['/visitors','Visitor Management',UserRoundCheck]],
  FACILITY_MANAGER: [['/ai-insights','AI Insights',BrainCircuit],['/collective-incidents','Collective Incidents',Network],['/knowledge-support','Knowledge Support',BookOpen],['/work-orders','Work Orders',ClipboardList],['/tickets','Tickets',ListChecks],['/residents','Residents',Users],['/vendors','Vendors',Building2],['/amenities','Amenities',CalendarDays],['/inventory','Inventory',Package],['/reports','Reports',FileBarChart]],
};
export default function Sidebar({ user, open, onClose }) { return <aside className={`sidebar ${open?'open':''}`}><div className="brand"><span className="brand-mark"><ShieldCheck size={22}/></span><div><strong>SafeHome</strong><small>Residential CRM</small></div><button className="sidebar-close" onClick={onClose} aria-label="Close navigation"><X/></button></div><div className="community-chip"><Building2 size={17}/><div><span>Community</span><strong>Green Valley</strong></div></div><p className="nav-label">Workspace</p><nav>{(links[user.role]||[]).map(([to,label,Icon])=><NavLink key={`${to}-${label}`} to={to} onClick={onClose}><Icon size={19}/><span>{label}</span><i/></NavLink>)}</nav><div className="prototype-note"><BrainCircuit size={18}/><p><strong>Phase 2 AI</strong><span>Claude reasoning with safe fallback</span></p></div></aside>; }
