import Incident from '../models/Incident.js';
import Ticket from '../models/Ticket.js';
import Notification from '../models/Notification.js';
import AuditLog from '../models/AuditLog.js';
import { writeAudit } from '../utils/audit.js';
import { AppError, asyncHandler, nextPublicId, ok, requireFields } from '../utils/http.js';

const filterFor = (user) => user.role === 'BLOCK_SUB_ADMIN' ? { blockId: user.blockId } : { communityId: user.communityId };
const find = async (user, id) => { const record = await Incident.findOne({ incidentId: id, ...filterFor(user) }); if (!record) throw new AppError(404, 'Incident not found in your access scope.'); return record; };
const audit = (record, user, action, details) => { record.timeline.push({ action, details, performedBy: user.userId }); return writeAudit({ action, entityType: 'Incident', entityId: record.incidentId, actorId: user.userId, message: details }); };
export const listIncidents = asyncHandler(async (req, res) => ok(res, await Incident.find(filterFor(req.user)).sort({ detectedAt: -1 }).lean()));
export const getIncident = asyncHandler(async (req, res) => ok(res, await find(req.user, req.params.id)));
export const updateIncidentStatus = asyncHandler(async (req, res) => { requireFields(req.body, ['status']); const allowed = ['DETECTED','MONITORING','ASSIGNED','RESOLVED','CLOSED','FALSE_POSITIVE']; if (!allowed.includes(req.body.status)) throw new AppError(400, 'Invalid incident status.'); const record = await find(req.user, req.params.id); record.status = req.body.status; if (['RESOLVED','CLOSED'].includes(record.status)) record.resolvedAt = new Date(); for (const field of ['title','category','severity','confidence']) if (req.body[field] !== undefined) record[field] = req.body[field]; await audit(record, req.user, 'INCIDENT_STATUS_UPDATED', `Incident updated to ${record.status}.`); await record.save(); ok(res, record); });
export const commentIncident = asyncHandler(async (req, res) => { requireFields(req.body, ['comment']); const record = await find(req.user, req.params.id); record.comments.push({ comment: req.body.comment, createdBy: req.user.userId }); await audit(record, req.user, 'INCIDENT_COMMENTED', 'Incident comment added.'); await record.save(); ok(res, record); });
export const assignIncident = asyncHandler(async (req, res) => { requireFields(req.body, ['assignedTo','assignedToType']); const record = await find(req.user, req.params.id); record.assignedTo=req.body.assignedTo; record.assignedToType=req.body.assignedToType; record.status='ASSIGNED'; await audit(record, req.user, 'INCIDENT_ASSIGNED', `Assigned to ${record.assignedToType} ${record.assignedTo}.`); await record.save(); ok(res, record); });
export const mergeTicket = asyncHandler(async (req, res) => { requireFields(req.body, ['ticketId']); const record = await find(req.user, req.params.id); const ticket=await Ticket.findOne({ticketId:req.body.ticketId,communityId:req.user.communityId}); if(!ticket)throw new AppError(404,'Ticket not found.'); if(!record.relatedTickets.includes(ticket.ticketId))record.relatedTickets.push(ticket.ticketId); ticket.relatedIncidentId=record.incidentId; await ticket.save(); await audit(record,req.user,'INCIDENT_TICKET_MERGED',`${ticket.ticketId} merged.`); await record.save(); ok(res,record); });
export const removeTicket = asyncHandler(async (req, res) => { requireFields(req.body,['ticketId']); const record=await find(req.user,req.params.id); record.relatedTickets=record.relatedTickets.filter((id)=>id!==req.body.ticketId); await Ticket.updateOne({ticketId:req.body.ticketId,relatedIncidentId:record.incidentId},{$set:{relatedIncidentId:null}}); await audit(record,req.user,'INCIDENT_TICKET_REMOVED',`${req.body.ticketId} removed.`); await record.save(); ok(res,record); });
export const notifyResidents = asyncHandler(async(req,res)=>{const record=await find(req.user,req.params.id);const tickets=await Ticket.find({ticketId:{$in:record.relatedTickets}}).lean();const residents=[...new Set(tickets.map((item)=>item.residentId))];const created=[];for(const userId of residents){const notificationId=await nextPublicId(Notification,'notificationId','N');created.push(await Notification.create({notificationId,userId,title:record.title,message:req.body.message||`An incident affecting your area is ${record.status}.`,type:'INCIDENT',entityType:'Incident',entityId:record.incidentId}));}await audit(record,req.user,'INCIDENT_RESIDENTS_NOTIFIED',`${created.length} affected residents notified.`);await record.save();ok(res,{notified:created.length});});
export const incidentAudit = asyncHandler(async(req,res)=>{await find(req.user,req.params.id);ok(res,await AuditLog.find({entityType:'Incident',entityId:req.params.id}).sort({createdAt:-1}).lean());});
