import { Router } from 'express';
import { aiInsights, detectIncidents, listIncidents, predictForTicket, recommendForTicket, reviewAIAnalysis } from '../controllers/aiController.js';
import { authenticate, authorize } from '../middleware/auth.js';
const router = Router(); router.use(authenticate);
router.get('/insights', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), aiInsights);
router.get('/incidents', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), listIncidents);
router.post('/recommend-technicians', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), recommendForTicket);
router.post('/predict-sla-risk', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), predictForTicket);
router.post('/detect-incidents', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), detectIncidents);
router.patch('/tickets/:ticketId/review', authorize('MAIN_ADMIN', 'BLOCK_SUB_ADMIN', 'FACILITY_MANAGER'), reviewAIAnalysis);
export default router;
