const permissions = {
  MAIN_ADMIN: ['SHOW_TICKETS','SHOW_SLA_RISK_TICKETS','SHOW_INCIDENTS','CREATE_TICKET','CREATE_BLOCK','CREATE_APARTMENT','CREATE_RESIDENT','CREATE_NOTICE','GENERATE_BILL','CREATE_VISITOR_REQUEST','CREATE_AMENITY_BOOKING','UPDATE_TICKET_STATUS','ASSIGN_TECHNICIAN','SHOW_BILLS','SHOW_WORK_ORDERS','RECOMMEND_TECHNICIAN','PREDICT_SLA_RISK','QUERY_KNOWLEDGE','SHOW_VISITORS','SHOW_REPORT_SUMMARY','BULK_CREATE_BLOCK_RESIDENTS'],
  BLOCK_SUB_ADMIN: ['SHOW_TICKETS','SHOW_SLA_RISK_TICKETS','SHOW_INCIDENTS','CREATE_TICKET','CREATE_RESIDENT','CREATE_NOTICE','GENERATE_BILL','CREATE_VISITOR_REQUEST','CREATE_AMENITY_BOOKING','UPDATE_TICKET_STATUS','ASSIGN_TECHNICIAN','SHOW_BILLS','SHOW_WORK_ORDERS','RECOMMEND_TECHNICIAN','PREDICT_SLA_RISK','QUERY_KNOWLEDGE','SHOW_VISITORS','SHOW_REPORT_SUMMARY'],
  RESIDENT: ['SHOW_TICKETS','CREATE_TICKET','CREATE_VISITOR_REQUEST','CREATE_AMENITY_BOOKING','SHOW_BILLS','QUERY_KNOWLEDGE','SHOW_VISITORS'],
  TECHNICIAN: ['SHOW_TICKETS','SHOW_WORK_ORDERS','UPDATE_TICKET_STATUS','QUERY_KNOWLEDGE'],
  SECURITY: ['SHOW_VISITORS', 'QUERY_KNOWLEDGE'],
  FACILITY_MANAGER: ['SHOW_TICKETS', 'SHOW_WORK_ORDERS', 'RECOMMEND_TECHNICIAN', 'PREDICT_SLA_RISK', 'QUERY_KNOWLEDGE', 'SHOW_REPORT_SUMMARY'],
};
export const canUseIntent = (role, intent) => intent !== 'UNKNOWN' && (permissions[role] || []).includes(intent);
export const sensitiveIntent = (intent) => ['CREATE_TICKET','CREATE_BLOCK','CREATE_APARTMENT','CREATE_RESIDENT','CREATE_NOTICE','GENERATE_BILL','CREATE_VISITOR_REQUEST','CREATE_AMENITY_BOOKING','UPDATE_TICKET_STATUS','ASSIGN_TECHNICIAN','BULK_CREATE_BLOCK_RESIDENTS'].includes(intent);
