const permissions = {
  MAIN_ADMIN: ['SHOW_TICKETS', 'CREATE_TICKET', 'SHOW_BILLS', 'SHOW_WORK_ORDERS', 'RECOMMEND_TECHNICIAN', 'PREDICT_SLA_RISK', 'QUERY_KNOWLEDGE', 'SHOW_VISITORS', 'SHOW_REPORT_SUMMARY', 'CREATE_NOTICE', 'BULK_CREATE_BLOCK_RESIDENTS'],
  BLOCK_SUB_ADMIN: ['SHOW_TICKETS', 'CREATE_TICKET', 'SHOW_BILLS', 'SHOW_WORK_ORDERS', 'RECOMMEND_TECHNICIAN', 'PREDICT_SLA_RISK', 'QUERY_KNOWLEDGE', 'SHOW_VISITORS', 'SHOW_REPORT_SUMMARY', 'CREATE_NOTICE'],
  RESIDENT: ['SHOW_TICKETS', 'CREATE_TICKET', 'SHOW_BILLS', 'QUERY_KNOWLEDGE', 'SHOW_VISITORS'],
  TECHNICIAN: ['SHOW_TICKETS', 'SHOW_WORK_ORDERS', 'QUERY_KNOWLEDGE'],
  SECURITY: ['SHOW_VISITORS', 'QUERY_KNOWLEDGE'],
  FACILITY_MANAGER: ['SHOW_TICKETS', 'SHOW_WORK_ORDERS', 'RECOMMEND_TECHNICIAN', 'PREDICT_SLA_RISK', 'QUERY_KNOWLEDGE', 'SHOW_REPORT_SUMMARY'],
};
export const canUseIntent = (role, intent) => intent !== 'UNKNOWN' && (permissions[role] || []).includes(intent);
export const sensitiveIntent = (intent) => ['CREATE_TICKET', 'CREATE_NOTICE', 'BULK_CREATE_BLOCK_RESIDENTS'].includes(intent);
